name: Hello World
# when to triggerthis pipeline . we avan trigger on push or manual or someother events like creating PR, updating PR, create branches, creating issues
on: [push] # tigger
jobs: # pipline . one workflow can have mutiple piplines
  hello:
    runs-on: ubuntu-latest # linux os , we can have windows
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - name: Print Hello World
        run: echo "Hello naresh!"