name: conditions
# when to triggerthis pipeline . we avan trigger on push or manual or someother events like creating PR, updating PR, create branches, creating issues
on: [push] # tigger
jobs: # pipline . one workflow can have mutiple piplines
  conditions:
    runs-on: ubuntu-latest # linux os , we can have windows
    steps:
      - name: step-1
        if: github.ref == 'refs/heads/main'
        run: echo "Hello AP!"
      - name: step2
        if: github.ref == 'refs/heads/feature-**'
        run: echo "Hello naresh!"